wget https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/Back.lua Back
wget https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/command.lua os/.command
wget https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/configure.lua os/.configure
wget https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/Logo.nfp os/Logo.nfp
wget https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/LogoCC.nfp os/LogoCC.nfp
wget https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/MPrograms.lua os/.MPrograms
wget https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/programs.lua os/.programs
wget https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/starter.lua startup
wget https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/system.lua os/.system
wget https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/Uninstall.lua os/.Uninstall
wget https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/updateOS.lua os/updateOS