shell.run("wget", "https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/Back.lua", "Back")
shell.run("wget", "https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/command.lua", "os/.command")
shell.run("wget", "https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/configure.lua", "os/configure")
shell.run("wget", "https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/Logo.nfp", "os/Logo.nfp")
shell.run("wget", "https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/LogoCC.nfp", "os/LogoCC.nfp")
shell.run("wget", "https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/MPrograms.lua", "os/.MPrograms")
shell.run("wget", "https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/programs.lua", "os/.programs")
shell.run("wget", "https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/starter.lua", "startup")
shell.run("wget", "https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/system.lua", "os/.system")
shell.run("wget", "https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/Uninstall.lua", "os/.Uninstall")
shell.run("wget", "https://ttabizt1337.github.io/TTOS-For-CC-Tweaked-Server/scripts/updateOS.lua", "os/updateOS")
shell.run("pastebin", "get", "yu4ASf1H", "FileSend.lua")
shell.run("pastebin", "get", "JeRVpe9M", "FileReceive.lua")
shell.run("pastebin", "get", "eppcxwUu", "FileGitDownload.lua")
shell.run("os/configure")
