speaker = peripheral.find("speaker")
term.clear()
speaker.playNote("pling", 1, 5)
sleep(0.2)
speaker.playNote("pling", 1, 10)
sleep(0.2)
speaker.playNote("pling", 1, 15)
sleep(0.2)
shell.run("os/.system")